import type { Student, Vehicle } from './types';

const school = 'Trường Thực Hành Sư Phạm';
const emptyPayments = {};

export const initialStudents: Student[] = [
  {
    id: 's1',
    name: 'Lê Nguyễn Minh Anh',
    className: '12',
    school,
    pickup: 'Hẻm bún riêu Cây Điều',
    parentName: 'Nguyễn Thị Thiệp',
    parentPhone: '0978948245',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's2',
    name: 'Đinh Văn Phúc Thái',
    className: '8A3',
    school,
    pickup: 'Đối diện nhà sách Bảo Quỳnh',
    parentName: 'Nguyễn Thị Mỹ Linh',
    parentPhone: '0359067888',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's3',
    name: 'Lê Thị Hà Phương',
    className: '9A2',
    school,
    pickup: 'Chợ Tân Mai',
    parentName: 'Lê Thị Hà',
    parentPhone: '0373176396',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's4',
    name: 'Hoàng Lê Minh Nga',
    className: '11A6',
    school,
    pickup: 'Đường D, Khu 97',
    parentName: 'Hoàng Minh Luân',
    parentPhone: '0989236712',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's5',
    name: 'Hoàng Thị Yến Nhi',
    className: '11A3',
    school,
    pickup: 'Đường C, Khu 94',
    parentName: 'Nguyễn Thị Ngân',
    parentPhone: '0985605919',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's6',
    name: 'Nguyễn Trần Phúc Nguyên',
    className: '9A11',
    school,
    pickup: 'Ngã Tư Thiết Giáp',
    parentName: 'Trần Thị Hiệp',
    parentPhone: '0985472306',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's7',
    name: 'Hoàng Thùy Linh',
    className: '11A2',
    school,
    pickup: 'Đường A, Khu 2007 (gần Bách hóa Thịnh Phát)',
    parentName: 'Chưa cập nhật',
    parentPhone: '0977826207',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's8',
    name: 'Cù Phú Quý',
    className: 'Chưa cập nhật',
    school,
    pickup: 'Đối diện nhà sách Bảo Quỳnh',
    parentName: 'Chưa cập nhật',
    parentPhone: '09678285',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's9',
    name: 'Lê Hà Đan',
    className: '11A6',
    school,
    pickup: 'Đường D, Khu 92 (hẻm 27, Nguyễn Khắc Hiếu)',
    parentName: 'Lê Thị Thúy Hà',
    parentPhone: '0377816747',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's10',
    name: 'Hoàng Thị Thanh Trúc',
    className: '9A10',
    school,
    pickup: 'Ngã 3 Thái Lan',
    parentName: 'Chưa cập nhật',
    parentPhone: '0948862385',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's11',
    name: 'Bùi Hoàng Đức',
    className: '8A8',
    school,
    pickup: 'Đường A, Khu 2007, Tổ 42',
    parentName: 'Chưa cập nhật',
    parentPhone: '0933825559',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's12',
    name: 'Trần Tú Quỳnh',
    className: '12A7',
    school,
    pickup: 'C3, Khu 97',
    parentName: 'Chưa cập nhật',
    parentPhone: '0983940734',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's13',
    name: 'Đinh Văn Đạt',
    className: '9',
    school,
    pickup: 'Đối diện Bida 38',
    parentName: 'Hiếu Linh',
    parentPhone: '0975736227',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's14',
    name: 'Nguyễn Lê Vân Anh',
    className: '11A7',
    school,
    pickup: 'UB phường Tam Phước',
    parentName: 'Lê Thị Thu Hằng',
    parentPhone: '0915323336',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
  {
    id: 's15',
    name: 'Nguyễn Gia Bảo',
    className: '9',
    school,
    pickup: 'Trường Tiểu học Tam Phước 4',
    parentName: 'Nguyễn Long',
    parentPhone: '0983080114',
    startDate: '2026-09-01',
    status: 'active',
    paymentHistory: emptyPayments,
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: 'v1',
    name: 'Xe 26271',
    plate: '26271',
    driver: 'Nguyễn Văn Dũng',
    driverPhone: '0903 452 118',
    route: 'Tam Phước → Biên Hòa',
    capacity: 29,
    status: 'active',
  },
  {
    id: 'v2',
    name: 'Xe 04312',
    plate: '04312',
    driver: 'Trần Thị Mai',
    driverPhone: '0918 770 214',
    route: 'Hòa Bình → Trấn Biên',
    capacity: 29,
    status: 'active',
  },
  {
    id: 'v3',
    name: 'Xe 03933',
    plate: '03933',
    driver: 'Lê Quốc Hùng',
    driverPhone: '0908 621 445',
    route: 'Long Bình → Trung tâm',
    capacity: 45,
    status: 'active',
  },
];
